#define DT7
// #define VT13
// #define FLYSKY
/*****************************************************************************/
/********** !!! WARNING: CODE GENERATED BY TAPROOT. DO NOT EDIT !!! **********/
/*****************************************************************************/

/*
 * Copyright (c) 2020-2022 Advanced Robotics at the University of Washington <robomstr@uw.edu>
 *
 * This file is part of Taproot.
 *
 * Taproot is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Taproot is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Taproot.  If not, see <https://www.gnu.org/licenses/>.
 */

#include "remote.hpp"

#include "tap/algorithms/math_user_utils.hpp"
#include "tap/architecture/clock.hpp"
#include "tap/communication/serial/uart.hpp"
#include "tap/control/remote_map_state.hpp"
#include "tap/drivers.hpp"
#include "tap/errors/create_errors.hpp"

#include "remote_serial_constants.hpp"

namespace tap::communication::serial
{
void Remote::initialize()
{
    drivers->uart.init<
        bound_ports::REMOTE_SERIAL_UART_PORT,
        bound_ports::REMOTE_BAUD_RATE,
        bound_ports::REMOTE_PARITY>();
}

void Remote::read()
{
    // Check disconnect timeout
    if (tap::arch::clock::getTimeMilliseconds() - lastRead > REMOTE_DISCONNECT_TIMEOUT)
    {
        connected = false;  // Remote no longer connected
        reset();            // Reset current remote values
    }
    uint8_t data;  // Next byte to be read
    // Read next byte if available and more needed for the current packet
    while (drivers->uart.read(bound_ports::REMOTE_SERIAL_UART_PORT, &data) &&
           currentBufferIndex < REMOTE_BUF_LEN)
    {
        rxBuffer[currentBufferIndex] = data;
        currentBufferIndex++;
        lastRead = tap::arch::clock::getTimeMilliseconds();
    }
    // Check read timeout
    if (tap::arch::clock::getTimeMilliseconds() - lastRead > REMOTE_READ_TIMEOUT)
    {
        clearRxBuffer();
    }
    // Parse buffer if all 18 bytes are read
    if (currentBufferIndex >= REMOTE_BUF_LEN)
    {
        connected = true;
        parseBuffer(rxBuffer);
        clearRxBuffer();
    }
}

bool Remote::isConnected() const { return connected; }

float Remote::getChannel(Channel ch) const
{
    switch (ch)
    {
        case Channel::RIGHT_HORIZONTAL:
            return remote.rightHorizontal / ANALOG_MAX_VALUE;
        case Channel::RIGHT_VERTICAL:
            return remote.rightVertical / ANALOG_MAX_VALUE;
        case Channel::LEFT_HORIZONTAL:
            return remote.leftHorizontal / ANALOG_MAX_VALUE;
        case Channel::LEFT_VERTICAL:
            return remote.leftVertical / ANALOG_MAX_VALUE;
        case Channel::WHEEL:
            return remote.wheel / ANALOG_MAX_VALUE;
    }
    return 0;
}

Remote::SwitchState Remote::getSwitch(Switch sw) const
{
    switch (sw)
    {
        case Switch::LEFT_SWITCH:
            return remote.leftSwitch;
        case Switch::RIGHT_SWITCH:
            return remote.rightSwitch;
    }
    return SwitchState::UNKNOWN;
}

void Remote::parseBuffer(uint8_t rxBuffer[REMOTE_BUF_LEN])
{
#ifdef DT7
    parseBufferDT7(rxBuffer);
#endif
#ifdef VT13
    parseBufferVT13(rxBuffer);
#endif
#ifdef FLYSKY
    parseBufferFlySky(rxBuffer);
#endif
}

void Remote::parseBufferDT7(uint8_t rxBuffer[REMOTE_BUF_LEN_DT7])
{
    // this is a wonky encoding implemented by our "good pal Li Qingzhi" as stated by a chinese
    // translated document our team acquired a while back; refer to this document for the protocol
    // encoding: https://drive.google.com/file/d/1a5kaTsDvG89KQwy3fkLVkxKaQJfJCsnu/view?usp=sharing

    // remote joystick information
    remote.rightHorizontal = (rxBuffer[0] | rxBuffer[1] << 8) & 0x07FF;
    remote.rightHorizontal -= 1024;
    remote.rightVertical = (rxBuffer[1] >> 3 | rxBuffer[2] << 5) & 0x07FF;
    remote.rightVertical -= 1024;
    remote.leftHorizontal = (rxBuffer[2] >> 6 | rxBuffer[3] << 2 | rxBuffer[4] << 10) & 0x07FF;
    remote.leftHorizontal -= 1024;
    remote.leftVertical = (rxBuffer[4] >> 1 | rxBuffer[5] << 7) & 0x07FF;
    remote.leftVertical -= 1024;

    remote.leftSwitch = static_cast<Remote::SwitchState>((rxBuffer[5] >> 6) & 0x03);
    remote.rightSwitch = static_cast<Remote::SwitchState>((rxBuffer[5] >> 4) & 0x03);

    // mouse input
    remote.mouse.x = rxBuffer[6] | (rxBuffer[7] << 8);    // x axis
    remote.mouse.y = rxBuffer[8] | (rxBuffer[9] << 8);    // y axis
    remote.mouse.z = rxBuffer[10] | (rxBuffer[11] << 8);  // z axis
    remote.mouse.l = static_cast<bool>(rxBuffer[12]);     // left button click
    remote.mouse.r = static_cast<bool>(rxBuffer[13]);     // right button click
    remote.mouse.m = 0;

    // keyboard capture
    remote.key = rxBuffer[14] | rxBuffer[15] << 8;
    // remote wheel
    remote.wheel = (rxBuffer[16] | rxBuffer[17] << 8) - 1024;

    // the remote joystick and wheel values must be <= abs(660)
    if ((abs(remote.rightHorizontal) > ANALOG_MAX_VALUE) ||
        (abs(remote.rightVertical) > ANALOG_MAX_VALUE) ||
        (abs(remote.leftHorizontal) > ANALOG_MAX_VALUE) ||
        (abs(remote.leftVertical) > ANALOG_MAX_VALUE) || (abs(remote.wheel) > ANALOG_MAX_VALUE))
    {
        RAISE_ERROR(drivers, "invalid remote joystick values");
    }

    tap::control::RemoteMapState mapState;
    mapState.initKeys(remote.key);
    mapState.updateState(*this);
    drivers->commandMapper.handleKeyStateChange(mapState);
    drivers->commandMapper.pollTriggerBindings();

    remote.updateCounter++;
}

void Remote::parseBufferVT13(uint8_t rxBuffer[REMOTE_BUF_LEN_VT13])
{
    lastRead = tap::arch::clock::getTimeMilliseconds();
    // remote joystick information
    remote.rightHorizontal = (rxBuffer[2] | rxBuffer[3] << 8) & 0x07FF;
    remote.rightHorizontal -= 1024;
    remote.rightVertical = (rxBuffer[3] >> 3 | rxBuffer[4] << 5) & 0x07FF;
    remote.rightVertical -= 1024;
    remote.leftVertical = (rxBuffer[4] >> 6 | rxBuffer[5] << 2 | rxBuffer[6] << 10) & 0x07FF;
    remote.leftVertical -= 1024;
    remote.leftHorizontal = (rxBuffer[6] >> 1 | rxBuffer[7] << 7) & 0x07FF;
    remote.leftHorizontal -= 1024;

    // switches / buttons
    remote.leftSwitch = static_cast<Remote::SwitchState>((rxBuffer[7] >> 4) & 0x03);
    // Cursed right switch logic
    remote.rightSwitch = static_cast<bool>((rxBuffer[7] >> 6) & 0x01)
                             ? Remote::SwitchState::DOWN
                             : remote.rightSwitch;  // pause
    remote.rightSwitch = static_cast<bool>((rxBuffer[7] >> 7) & 0x01)
                             ? Remote::SwitchState::MID
                             : remote.rightSwitch;  // leftButton
    remote.rightSwitch = static_cast<bool>(rxBuffer[8] & 0x01) ? Remote::SwitchState::UP
                                                               : remote.rightSwitch;  // rightButton

    // remote dial
    remote.wheel = (rxBuffer[8] >> 1 | rxBuffer[9] << 7) & 0x07FF;
    remote.wheel -= 1024;

    // = static_cast<bool>((rxBuffer[7] >> 4) & 0x01); trigger not used?

    // mouse input
    remote.mouse.x = rxBuffer[10] | (rxBuffer[11] << 8);  // x axis
    remote.mouse.y = rxBuffer[12] | (rxBuffer[13] << 8);  // y axis
    remote.mouse.z = rxBuffer[14] | (rxBuffer[15] << 8);  // z axis (scroll)
    remote.mouse.l = rxBuffer[16] & 0x03;                 // left button
    remote.mouse.r = (rxBuffer[16] >> 2) & 0x03;          // right button
    remote.mouse.m = (rxBuffer[16] >> 4) & 0x03;          // middle button

    // keyboard capture
    remote.key = rxBuffer[17] | (rxBuffer[18] << 8);

    // crc validation capture
    // remote.crc = rxBuffer[19] | (rxBuffer[20] << 8);

    // the remote joystick and dial values must be <= abs(660)
    if ((abs(remote.rightHorizontal) > ANALOG_MAX_VALUE) ||
        (abs(remote.rightVertical) > ANALOG_MAX_VALUE) ||
        (abs(remote.leftHorizontal) > ANALOG_MAX_VALUE) ||
        (abs(remote.leftVertical) > ANALOG_MAX_VALUE) || (abs(remote.wheel) > ANALOG_MAX_VALUE))
    {
        RAISE_ERROR(drivers, "invalid remote joystick values");
    }

    tap::control::RemoteMapState mapState;
    mapState.initKeys(remote.key);
    mapState.updateState(*this);
    drivers->commandMapper.handleKeyStateChange(mapState);
    drivers->commandMapper.pollTriggerBindings();

    remote.updateCounter++;
}

void Remote::parseBufferFlySky(uint8_t rxBuffer[REMOTE_BUF_LEN_FLY_SKY])
{
    lastRead = tap::arch::clock::getTimeMilliseconds();
    // --- FLYSKY i-BUS PARSING ---
    // Assuming rxBuffer is your 32-byte incoming frame

    // Helper lambda to unpack, center, and scale the joystick values
    auto parse_and_scale = [](uint8_t low_byte, uint8_t high_byte) -> int16_t {
        int32_t raw = low_byte | (high_byte << 8);
        // Center at 0 (raw - 1500) and scale by 1.32 to hit -660 to 660
        return static_cast<int16_t>((raw - 1500) * 1.32);
    };

    // 1. Remote Joysticks (Channels 1-4)
    remote.rightHorizontal = parse_and_scale(rxBuffer[2], rxBuffer[3]);  // CH1: Aileron
    remote.rightVertical = parse_and_scale(rxBuffer[4], rxBuffer[5]);    // CH2: Elevator
    remote.leftVertical = parse_and_scale(rxBuffer[6], rxBuffer[7]);     // CH3: Throttle
    remote.leftHorizontal = parse_and_scale(rxBuffer[8], rxBuffer[9]);   // CH4: Rudder

    // 2. Dials / Knobs (Channels 5-6)
    // (Assuming you want these scaled to -660 to 660 as well)
    remote.wheel = parse_and_scale(rxBuffer[10], rxBuffer[11]);  // CH5 VRA
    // remote.dialVrB = parse_and_scale(rxBuffer[12], rxBuffer[13]);  // CH6

    // 3. Switches (Channels 7-10)
    auto parse_switch = [](uint8_t low, uint8_t high) -> Remote::SwitchState {
        uint16_t raw_val = low | (high << 8);
        if (raw_val < 1300) return Remote::SwitchState::UP;
        if (raw_val > 1700) return Remote::SwitchState::DOWN;
        return Remote::SwitchState::MID;
    };

    remote.leftSwitch =
        parse_switch(rxBuffer[14], rxBuffer[15]) == Remote::SwitchState::UP
            ? Remote::SwitchState::MID
            : parse_switch(
                  rxBuffer[16],
                  rxBuffer[17]);  // If SWA up mid, otherwise up or down based on SWB
    remote.rightSwitch = parse_switch(rxBuffer[18], rxBuffer[19]);                    // CH9 SWC
    connected = parse_switch(rxBuffer[20], rxBuffer[21]) == Remote::SwitchState::UP;  // CH10 SWD

    // mouse input
    remote.mouse.x = 0;
    remote.mouse.y = 0;
    remote.mouse.z = 0;
    remote.mouse.l = 0;
    remote.mouse.r = 0;
    remote.mouse.m = 0;

    // keyboard capture
    remote.key = 0;

    if ((abs(remote.rightHorizontal) > ANALOG_MAX_VALUE) ||
        (abs(remote.rightVertical) > ANALOG_MAX_VALUE) ||
        (abs(remote.leftHorizontal) > ANALOG_MAX_VALUE) ||
        (abs(remote.leftVertical) > ANALOG_MAX_VALUE) || (abs(remote.wheel) > ANALOG_MAX_VALUE))
    {
        RAISE_ERROR(drivers, "invalid remote joystick values");
    }

    tap::control::RemoteMapState mapState;
    mapState.initKeys(remote.key);
    mapState.updateState(*this);
    drivers->commandMapper.handleKeyStateChange(mapState);
    drivers->commandMapper.pollTriggerBindings();

    remote.updateCounter++;
}

void Remote::clearRxBuffer()
{
    // Reset bytes read counter
    currentBufferIndex = 0;
    // Clear remote rxBuffer
    for (int i = 0; i < REMOTE_BUF_LEN_DT7; i++)
    {
        rxBuffer[i] = 0;
    }
    // Clear Usart1 rxBuffer
    drivers->uart.discardReceiveBuffer(bound_ports::REMOTE_SERIAL_UART_PORT);
}

void Remote::reset()
{
    remote.rightHorizontal = 0;
    remote.rightVertical = 0;
    remote.leftHorizontal = 0;
    remote.leftVertical = 0;
    remote.leftSwitch = SwitchState::UNKNOWN;
    remote.rightSwitch = SwitchState::UNKNOWN;
    remote.mouse.x = 0;
    remote.mouse.y = 0;
    remote.mouse.z = 0;
    remote.mouse.l = 0;
    remote.mouse.r = 0;
    remote.mouse.m = 0;
    remote.key = 0;
    remote.wheel = 0;
    clearRxBuffer();
}

uint32_t Remote::getUpdateCounter() const { return remote.updateCounter; }

}  // namespace tap::communication::serial
