/*****************************************************************************/
/********** !!! WARNING: CODE GENERATED BY TAPROOT. DO NOT EDIT !!! **********/
/*****************************************************************************/

/*
 * Copyright (c) 2020-2021 Advanced Robotics at the University of Washington <robomstr@uw.edu>
 *
 * This file is part of Taproot.
 *
 * Taproot is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Taproot is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Taproot.  If not, see <https://www.gnu.org/licenses/>.
 */

#include "remote_map_state.hpp"

#include "tap/errors/create_errors.hpp"

using namespace tap::communication::serial;
namespace tap
{
namespace control
{
RemoteMapState::RemoteMapState(
    tap::communication::serial::Remote::SwitchState leftss,
    tap::communication::serial::Remote::SwitchState rightss,
    const std::list<tap::communication::serial::Remote::Key> &keySet,
    const std::list<tap::communication::serial::Remote::Key> &negKeySet,
    bool mouseButtonLeftPressed,
    bool mouseButtonRightPressed,
    bool mouseButtonMiddlePressed)
{
    initLSwitch(leftss);
    initRSwitch(rightss);
    initKeys(keySet);
    initNegKeys(negKeySet);
    if (mouseButtonLeftPressed)
    {
        initLMouseButton();
    }
    if (mouseButtonRightPressed)
    {
        initRMouseButton();
    }
    if (mouseButtonMiddlePressed)
    {
        initMMouseButton();
    }
}

RemoteMapState::RemoteMapState(Remote::Switch swh, Remote::SwitchState switchState)
{
    if (swh == Remote::Switch::LEFT_SWITCH)
    {
        initLSwitch(switchState);
    }
    else
    {
        initRSwitch(switchState);
    }
}

RemoteMapState::RemoteMapState(Remote::SwitchState leftss, Remote::SwitchState rightss)
{
    initLSwitch(leftss);
    initRSwitch(rightss);
}

RemoteMapState::RemoteMapState(
    const std::list<Remote::Key> &keySet,
    const std::list<Remote::Key> &negKeySet)
{
    initKeys(keySet);
    initNegKeys(negKeySet);
}

RemoteMapState::RemoteMapState(
    RemoteMapState::MouseButton button,
    const std::list<Remote::Key> &keySet,
    const std::list<Remote::Key> &negKeySet)
{
    switch (button)
    {
        case MouseButton::LEFT:
            initLMouseButton();
            break;
        case MouseButton::RIGHT:
            initRMouseButton();
            break;
        case MouseButton::Middle:
            initMMouseButton();
            break;
        default:
            break;
    }

    initKeys(keySet);
    initNegKeys(negKeySet);
}

RemoteMapState::RemoteMapState(MouseButton button)
{
    switch (button)
    {
        case MouseButton::LEFT:
            initLMouseButton();
            break;
        case MouseButton::RIGHT:
            initRMouseButton();
            break;
        case MouseButton::Middle:
            initMMouseButton();
            break;
        default:
            break;
    }
}

void RemoteMapState::updateState(tap::communication::serial::Remote &remote)
{
    initLSwitch(remote.getSwitch(Remote::Switch::LEFT_SWITCH));
    initRSwitch(remote.getSwitch(Remote::Switch::RIGHT_SWITCH));
    if (remote.getMouseL()) initLMouseButton();
    if (remote.getMouseR()) initRMouseButton();
    if (remote.getMouseM()) initMMouseButton();
}

void RemoteMapState::initLSwitch(Remote::SwitchState ss) { lSwitch = ss; }

void RemoteMapState::initRSwitch(Remote::SwitchState ss) { rSwitch = ss; }

void RemoteMapState::initLMouseButton() { lMouseButton = true; }

void RemoteMapState::initRMouseButton() { rMouseButton = true; }

void RemoteMapState::initMMouseButton() { mMouseButton = true; }

bool RemoteMapState::stateSubsetOf(const GenericRemoteMapState &other) const
{
    auto &rOther = static_cast<const RemoteMapState &>(other);
    if (rSwitch != Remote::SwitchState::UNKNOWN && rSwitch != rOther.rSwitch) return false;
    if (lSwitch != Remote::SwitchState::UNKNOWN && lSwitch != rOther.lSwitch) return false;
    if (!GenericRemoteMapState::stateSubsetOf(other)) return false;
    if (lMouseButton && !rOther.lMouseButton) return false;
    if (rMouseButton && !rOther.rMouseButton) return false;
    if (mMouseButton && !rOther.mMouseButton) return false;
    return true;
}

bool operator==(const RemoteMapState &rms1, const RemoteMapState &rms2)
{
    return rms1.getLSwitch() == rms2.getLSwitch() && rms1.getRSwitch() == rms2.getRSwitch() &&
           rms1.keys == rms2.keys && rms1.negKeys == rms2.negKeys &&
           rms1.getLMouseButton() == rms2.getLMouseButton() &&
           rms1.getRMouseButton() == rms2.getRMouseButton() &&
           rms1.getMMouseButton() == rms2.getMMouseButton();
}

bool operator!=(const RemoteMapState &rms1, const RemoteMapState &rms2) { return !(rms1 == rms2); }

}  // namespace control
}  // namespace tap
